### ISSUE TITLE
Layer.start vs Layer.offset

### ISSUE THREAD

**Issue by echo66** [wavesjs/waves-ui#20]
Greetings!

Can anyone explain what is the practical difference between both attributes? I don't get it, sorry. :/

Thanks in advance!

**Comment by b-ma** [comment]
Hey @echo66 ,

Basically the `start` attribute is the time at which your layer starts to be displayed from the origin of the timeline. The `offset` is relative to the `start` value and basically allow to decay your data according to this `start` value.

For example, if you have an audio file of 4 seconds to render, but you want to display only the last second of the file at 2 second in the timeline, your layer would have the following attributes:
```
layer.start = 2;
layer.offset = -3;
layer.duration = 1;
```
You can also see it as a way to crop left in a layer, while the `duration` attribute would allow you to crop right.

You can find a scheme here: https://github.com/wavesjs/ui/blob/master/src/core/layer-time-context.js#L22. We will provide a more graphical one soon in the documentation.

Hope I'm clear,

**Comment by echo66** [comment]
Thanks for the (very) clear explanation, Benjamin. Another (related) question: are you guys planning to manage the DOM removal/insertion of items related to the datums, according to *start*, *offset* and *duration* ? For example, imagine that you have a marker layer to display the beat grid. Instead of inserting 800+ beats in the DOM, you could just insert the one that are visible, according to *start*, *offset* and *duration*.

**Comment by b-ma** [comment]
Hey @echo66 ,

Yes something like this is planned, even if I'm not sure it be would handled exactly the way you describe it, because this approach at the `render` level would lead to a lot of DOM manipulation that could become very problematic. The thing we add in mind is more at the `update` level: all the elements would inserted in the DOM but we would only update the ones present in the visible area (and eventually `display:hidden` all the others).

The `WaveformShape` implements a kind of messy prototype of this principle, to be cleaner we should add some `minVisibleX` and `maxVisibleX` (or maybe in time domain) attributes to the `renderingContext` and rewrite the `update` methods of the shape(s) to use these values.

**Comment by echo66** [comment]
Again, thanks for the very clear explanation, Benjamin. :+1: 
If the number of changes in the DOM is problematic, why did you opted to implement visibility control for the Axis class and the available generators?

**Comment by b-ma** [comment]
Haha good question ! I guess the problem with axis is that they potentially go from -infinity to infinity, so we have to create a limit somewhere...

**Comment by echo66** [comment]
Yes, I know that. The point I want to make is that if you implemented that control in the Axis generators and I do not notice any slow downs or dropouts (I guess these were the potential issues you were trying to avoid when updating the DOM so frequently).
